FROM ubuntu:latest

COPY --from=golang:1.18 /usr/local/go/ /usr/local/go/
ENV PATH="/usr/local/go/bin:${PATH}"

RUN apt-get update && apt-get install -y ca-certificates pkg-config libmagickcore-dev libmagickwand-dev

WORKDIR /app
