// Code generated by enum_generator; DO NOT EDIT.
//
//go:generate go run enum_generator.go ColorspaceType colorspace_type.go
package types

import (
	"fmt"

	"go.starlark.net/starlark"
	"gopkg.in/gographics/imagick.v2/imagick"
)

type ColorspaceType struct {
	Value     imagick.ColorspaceType
	stringVal string
}

func (v ColorspaceType) String() string {
	return fmt.Sprintf("ColorspaceType %s", v.stringVal)
}

func (v ColorspaceType) Type() string {
	return "ColorspaceType"
}

func (v ColorspaceType) Freeze() {
	return
}

func (v ColorspaceType) Truth() starlark.Bool {
	return true
}

func (v ColorspaceType) Hash() (uint32, error) {
	return uint32(v.Value), nil
}

var _ starlark.Value = (*ColorspaceType)(nil)

var _ColorspaceTypeMap = map[string]ColorspaceType{
	"COLORSPACE_UNDEFINED":   {imagick.COLORSPACE_UNDEFINED, "COLORSPACE_UNDEFINED"},
	"COLORSPACE_RGB":         {imagick.COLORSPACE_RGB, "COLORSPACE_RGB"},
	"COLORSPACE_GRAY":        {imagick.COLORSPACE_GRAY, "COLORSPACE_GRAY"},
	"COLORSPACE_TRANSPARENT": {imagick.COLORSPACE_TRANSPARENT, "COLORSPACE_TRANSPARENT"},
	"COLORSPACE_OHTA":        {imagick.COLORSPACE_OHTA, "COLORSPACE_OHTA"},
	"COLORSPACE_LAB":         {imagick.COLORSPACE_LAB, "COLORSPACE_LAB"},
	"COLORSPACE_XYZ":         {imagick.COLORSPACE_XYZ, "COLORSPACE_XYZ"},
	"COLORSPACE_YCBCR":       {imagick.COLORSPACE_YCBCR, "COLORSPACE_YCBCR"},
	"COLORSPACE_YCC":         {imagick.COLORSPACE_YCC, "COLORSPACE_YCC"},
	"COLORSPACE_YIQ":         {imagick.COLORSPACE_YIQ, "COLORSPACE_YIQ"},
	"COLORSPACE_YPBPR":       {imagick.COLORSPACE_YPBPR, "COLORSPACE_YPBPR"},
	"COLORSPACE_YUV":         {imagick.COLORSPACE_YUV, "COLORSPACE_YUV"},
	"COLORSPACE_CMYK":        {imagick.COLORSPACE_CMYK, "COLORSPACE_CMYK"},
	"COLORSPACE_SRGB":        {imagick.COLORSPACE_SRGB, "COLORSPACE_SRGB"},
	"COLORSPACE_HSB":         {imagick.COLORSPACE_HSB, "COLORSPACE_HSB"},
	"COLORSPACE_HSL":         {imagick.COLORSPACE_HSL, "COLORSPACE_HSL"},
	"COLORSPACE_HWB":         {imagick.COLORSPACE_HWB, "COLORSPACE_HWB"},
	"COLORSPACE_REC601LUMA":  {imagick.COLORSPACE_REC601LUMA, "COLORSPACE_REC601LUMA"},
	"COLORSPACE_REC601YCBCR": {imagick.COLORSPACE_REC601YCBCR, "COLORSPACE_REC601YCBCR"},
	"COLORSPACE_REC709LUMA":  {imagick.COLORSPACE_REC709LUMA, "COLORSPACE_REC709LUMA"},
	"COLORSPACE_REC709YCBCR": {imagick.COLORSPACE_REC709YCBCR, "COLORSPACE_REC709YCBCR"},
	"COLORSPACE_LOG":         {imagick.COLORSPACE_LOG, "COLORSPACE_LOG"},
	"COLORSPACE_CMY":         {imagick.COLORSPACE_CMY, "COLORSPACE_CMY"},
}

var _ColorspaceTypeNames = []string{
	"COLORSPACE_UNDEFINED",
	"COLORSPACE_RGB",
	"COLORSPACE_GRAY",
	"COLORSPACE_TRANSPARENT",
	"COLORSPACE_OHTA",
	"COLORSPACE_LAB",
	"COLORSPACE_XYZ",
	"COLORSPACE_YCBCR",
	"COLORSPACE_YCC",
	"COLORSPACE_YIQ",
	"COLORSPACE_YPBPR",
	"COLORSPACE_YUV",
	"COLORSPACE_CMYK",
	"COLORSPACE_SRGB",
	"COLORSPACE_HSB",
	"COLORSPACE_HSL",
	"COLORSPACE_HWB",
	"COLORSPACE_REC601LUMA",
	"COLORSPACE_REC601YCBCR",
	"COLORSPACE_REC709LUMA",
	"COLORSPACE_REC709YCBCR",
	"COLORSPACE_LOG",
	"COLORSPACE_CMY",
}

type ColorspaceTypeEnum struct{}

func (v ColorspaceTypeEnum) String() string {
	return "ColorspaceTypeEnum"
}

func (v ColorspaceTypeEnum) Type() string {
	return "ColorspaceTypeEnum"
}

func (v ColorspaceTypeEnum) Freeze() {
	return
}

func (v ColorspaceTypeEnum) Truth() starlark.Bool {
	return true
}

func (v ColorspaceTypeEnum) Hash() (uint32, error) {
	return 0, nil
}

func (v ColorspaceTypeEnum) Attr(name string) (starlark.Value, error) {
	val, found := _ColorspaceTypeMap[name]
	if !found {
		return nil, starlark.NoSuchAttrError(fmt.Sprintf("unknown ColorspaceType %s", name))
	}
	return val, nil
}

func (v ColorspaceTypeEnum) AttrNames() []string {
	return _ColorspaceTypeNames
}

var _ starlark.Value = (*ColorspaceTypeEnum)(nil)
var _ starlark.HasAttrs = (*ColorspaceTypeEnum)(nil)
