// Code generated by enum_generator; DO NOT EDIT.
//
//go:generate go run enum_generator.go
package enums

import (
	"fmt"

	"go.starlark.net/starlark"
	"gopkg.in/gographics/imagick.v3/imagick"
)

type ColorspaceType struct {
	Value     imagick.ColorspaceType
	stringVal string
}

func (v ColorspaceType) String() string {
	return fmt.Sprintf("ColorspaceType %s", v.stringVal)
}

func (v ColorspaceType) Type() string {
	return "ColorspaceType"
}

func (v ColorspaceType) Freeze() {
	return
}

func (v ColorspaceType) Truth() starlark.Bool {
	return true
}

func (v ColorspaceType) Hash() (uint32, error) {
	return uint32(v.Value), nil
}

var _ starlark.Value = (*ColorspaceType)(nil)

var _ColorspaceTypeMap = map[string]ColorspaceType{
	"COLORSPACE_UNDEFINED":   {imagick.COLORSPACE_UNDEFINED, "COLORSPACE_UNDEFINED"},
	"COLORSPACE_CMY":         {imagick.COLORSPACE_CMY, "COLORSPACE_CMY"},
	"COLORSPACE_CMYK":        {imagick.COLORSPACE_CMYK, "COLORSPACE_CMYK"},
	"COLORSPACE_GRAY":        {imagick.COLORSPACE_GRAY, "COLORSPACE_GRAY"},
	"COLORSPACE_HCL":         {imagick.COLORSPACE_HCL, "COLORSPACE_HCL"},
	"COLORSPACE_HCLP":        {imagick.COLORSPACE_HCLP, "COLORSPACE_HCLP"},
	"COLORSPACE_HSB":         {imagick.COLORSPACE_HSB, "COLORSPACE_HSB"},
	"COLORSPACE_HSI":         {imagick.COLORSPACE_HSI, "COLORSPACE_HSI"},
	"COLORSPACE_HSL":         {imagick.COLORSPACE_HSL, "COLORSPACE_HSL"},
	"COLORSPACE_HSV":         {imagick.COLORSPACE_HSV, "COLORSPACE_HSV"},
	"COLORSPACE_HWB":         {imagick.COLORSPACE_HWB, "COLORSPACE_HWB"},
	"COLORSPACE_LAB":         {imagick.COLORSPACE_LAB, "COLORSPACE_LAB"},
	"COLORSPACE_LCH":         {imagick.COLORSPACE_LCH, "COLORSPACE_LCH"},
	"COLORSPACE_LCHAB":       {imagick.COLORSPACE_LCHAB, "COLORSPACE_LCHAB"},
	"COLORSPACE_LCHUV":       {imagick.COLORSPACE_LCHUV, "COLORSPACE_LCHUV"},
	"COLORSPACE_LMS":         {imagick.COLORSPACE_LMS, "COLORSPACE_LMS"},
	"COLORSPACE_LOG":         {imagick.COLORSPACE_LOG, "COLORSPACE_LOG"},
	"COLORSPACE_LUV":         {imagick.COLORSPACE_LUV, "COLORSPACE_LUV"},
	"COLORSPACE_OHTA":        {imagick.COLORSPACE_OHTA, "COLORSPACE_OHTA"},
	"COLORSPACE_REC601YCBCR": {imagick.COLORSPACE_REC601YCBCR, "COLORSPACE_REC601YCBCR"},
	"COLORSPACE_REC709YCBCR": {imagick.COLORSPACE_REC709YCBCR, "COLORSPACE_REC709YCBCR"},
	"COLORSPACE_RGB":         {imagick.COLORSPACE_RGB, "COLORSPACE_RGB"},
	"COLORSPACE_SCRGB":       {imagick.COLORSPACE_SCRGB, "COLORSPACE_SCRGB"},
	"COLORSPACE_SRGB":        {imagick.COLORSPACE_SRGB, "COLORSPACE_SRGB"},
	"COLORSPACE_TRANSPARENT": {imagick.COLORSPACE_TRANSPARENT, "COLORSPACE_TRANSPARENT"},
	"COLORSPACE_XYY":         {imagick.COLORSPACE_XYY, "COLORSPACE_XYY"},
	"COLORSPACE_XYZ":         {imagick.COLORSPACE_XYZ, "COLORSPACE_XYZ"},
	"COLORSPACE_YCBCR":       {imagick.COLORSPACE_YCBCR, "COLORSPACE_YCBCR"},
	"COLORSPACE_YCC":         {imagick.COLORSPACE_YCC, "COLORSPACE_YCC"},
	"COLORSPACE_YDDDR":       {imagick.COLORSPACE_YDDDR, "COLORSPACE_YDDDR"},
	"COLORSPACE_YIQ":         {imagick.COLORSPACE_YIQ, "COLORSPACE_YIQ"},
	"COLORSPACE_YPBPR":       {imagick.COLORSPACE_YPBPR, "COLORSPACE_YPBPR"},
	"COLORSPACE_YUV":         {imagick.COLORSPACE_YUV, "COLORSPACE_YUV"},
}

var _ColorspaceTypeNames = []string{
	"COLORSPACE_UNDEFINED",
	"COLORSPACE_CMY",
	"COLORSPACE_CMYK",
	"COLORSPACE_GRAY",
	"COLORSPACE_HCL",
	"COLORSPACE_HCLP",
	"COLORSPACE_HSB",
	"COLORSPACE_HSI",
	"COLORSPACE_HSL",
	"COLORSPACE_HSV",
	"COLORSPACE_HWB",
	"COLORSPACE_LAB",
	"COLORSPACE_LCH",
	"COLORSPACE_LCHAB",
	"COLORSPACE_LCHUV",
	"COLORSPACE_LMS",
	"COLORSPACE_LOG",
	"COLORSPACE_LUV",
	"COLORSPACE_OHTA",
	"COLORSPACE_REC601YCBCR",
	"COLORSPACE_REC709YCBCR",
	"COLORSPACE_RGB",
	"COLORSPACE_SCRGB",
	"COLORSPACE_SRGB",
	"COLORSPACE_TRANSPARENT",
	"COLORSPACE_XYY",
	"COLORSPACE_XYZ",
	"COLORSPACE_YCBCR",
	"COLORSPACE_YCC",
	"COLORSPACE_YDDDR",
	"COLORSPACE_YIQ",
	"COLORSPACE_YPBPR",
	"COLORSPACE_YUV",
}

type ColorspaceTypeEnum struct{}

func (v ColorspaceTypeEnum) String() string {
	return "ColorspaceTypeEnum"
}

func (v ColorspaceTypeEnum) Type() string {
	return "ColorspaceTypeEnum"
}

func (v ColorspaceTypeEnum) Freeze() {
	return
}

func (v ColorspaceTypeEnum) Truth() starlark.Bool {
	return true
}

func (v ColorspaceTypeEnum) Hash() (uint32, error) {
	return 0, nil
}

func (v ColorspaceTypeEnum) Attr(name string) (starlark.Value, error) {
	val, found := _ColorspaceTypeMap[name]
	if !found {
		return nil, starlark.NoSuchAttrError(fmt.Sprintf("unknown ColorspaceType %s", name))
	}
	return val, nil
}

func (v ColorspaceTypeEnum) AttrNames() []string {
	return _ColorspaceTypeNames
}

var _ starlark.Value = (*ColorspaceTypeEnum)(nil)
var _ starlark.HasAttrs = (*ColorspaceTypeEnum)(nil)
